// Fetch departments action types

export const FETCH_DEPARTMENTS_START = "FETCH_DEPARTMENTS_START";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";
export const FETCH_DEPARTMENTS_FAILURE = "FETCH_DEPARTMENTS_FAILURE";
