// Fetch product review  actions types
export const FETCH_PRODUCT_REVIEWS_START = "FETCH_PRODUCT_REVIEWS_START";
export const FETCH_PRODUCT_REVIEWS_SUCCESS = "FETCH_PRODUCT_REVIEWS_SUCCESS";
export const FETCH_PRODUCT_REVIEWS_FAILURE = "FETCH_PRODUCT_REVIEWS_FAILURE";
