// Add to cart types
export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

// Generate cart ID types
export const GENERATE_CART_ID_START = "GENERATE_CART_ID_START";
export const GENERATE_CART_ID_SUCCESS = "GENERATE_CART_ID_SUCCESS";
export const GENERATE_CART_ID_FAILURE = "GENERATE_CART_ID_FAILURE";
export const GET_CART_ID_LOCAL = "GET_CART_ID_LOCAL";

// Update Product inCart

export const UPDATE_PRODUCT_INCART_START = "UPDATE_PRODUCT_INCART_START";
export const UPDATE_PRODUCT_INCART_SUCCESS = "UPDATE_PRODUCT_INCART_SUCCESS";
export const UPDATE_PRODUCT_INCART_FAILURE = "UPDATE_PRODUCT_INCART_FAILURE";
// Get Products inCart

export const GET_PRODUCT_INCART_START = "GET_PRODUCT_INCART_START";
export const GET_PRODUCT_INCART_SUCCESS = "GET_PRODUCT_INCART_SUCCESS";
export const GET_PRODUCT_INCART_FAILURE = "GET_PRODUCT_INCART_FAILURE";

// Remove Product InCart

export const REMOVE_PRODUCT_INCART_START = "REMOVE_PRODUCT_INCART_START";
export const REMOVE_PRODUCT_INCART_SUCCESS = "REMOVE_PRODUCT_INCART_SUCCESS";
export const REMOVE_PRODUCT_INCART_FAILURE = "REMOVE_PRODUCT_INCART_FAILURE";
