export const FETCH_REGIONS_START = "FETCH_REGIONS_START";
export const FETCH_REGIONS_SUCCESS = "FETCH_REGIONS_SUCCESS";
export const FETCH_REGIONS_FAILURE = "FETCH_REGIONS_FAILURE";

export const FETCH_SHIPPING_OPTIONS_START = "FETCH_SHIPPING_OPTIONS_START";
export const FETCH_SHIPPING_OPTIONS_SUCCESS = "FETCH_SHIPPING_OPTIONS_SUCCESS";
export const FETCH_SHIPPING_OPTIONS_FAILURE = "FETCH_SHIPPING_OPTIONS_FAILURE";

export const UPDATE_SHIPPING_REGION = "UPDATE_SHIPPING_REGION";
