export const FETCH_REGIONS_START = "FETCH_REGIONS_START";
export const FETCH_REGIONS_SUCCESS = "FETCH_REGIONS_SUCCESS";
export const FETCH_REGIONS_FAILURE = "FETCH_REGIONS_FAILURE";

export const UPDATE_SHIPPING_REGION = "UPDATE_SHIPPING_REGION";
