// Fetch Product attributes types
export const FETCH_PRODUCT_ATTRIBUTES_START = "FETCH_PRODUCT_ATTRIBUTES_START";
export const FETCH_PRODUCT_ATTRIBUTES_SUCCESS =
  "FETCH_PRODUCT_ATTRIBUTES_SUCCESS";
export const FETCH_PRODUCT_ATTRIBUTES_FAILURE =
  "FETCH_PRODUCT_ATTRIBUTES_FAILURE";
